dist: trusty

language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

install: true
script: "./gradlew build -x copyDistFiles"

script:
  - ./gradlew clean build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
 email:
   recipients:
      - treadz11@gmail.com
   on_failure: always